{% set name = "sphinx-llm" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx_llm-{{ version }}.tar.gz
  sha256: bff0b4650e9a80b2a27223b3b5b155a5e631c300d4fb6dcef1522168ac590a82

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - sphinx-markdown-builder >=0.6.8
    - sphinx >=7.4.7

test:
  imports:
    - sphinx_llm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jacobtomlinson/sphinx-llm
  summary: LLM extensions for Sphinx
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
